name: pytorch-1.0
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_1003
  - ca-certificates=2018.11.29=ha4d7672_0
  - certifi=2018.11.29=py36_1000
  - chardet=3.0.4=py36_1003
  - cryptography=2.3.1=py36hdffb7b8_0
  - cryptography-vectors=2.3.1=py36_1000
  - idna=2.8=py36_1000
  - libsodium=1.0.16=h470a237_1
  - openssl=1.0.2p=h470a237_2
  - pyopenssl=18.0.0=py36_1000
  - pysocks=1.6.8=py36_1002
  - python=3.6.6=h5001a0f_3
  - pyzmq=17.1.2=py36hae99301_1
  - requests=2.21.0=py36_1000
  - torchfile=0.1.0=py_0
  - urllib3=1.24.1=py36_1000
  - visdom=0.1.8.5=0
  - websocket-client=0.54.0=py36_1000
  - zeromq=4.2.5=hfc679d8_6
  - autopep8=1.4.3=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - cffi=1.11.5=py36he75722e_1
  - cycler=0.10.0=py36_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py36_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py36h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.1=144
  - ipython=7.2.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - jedi=0.13.1=py36_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.0.1=py36hf484d3e_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.35=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - matplotlib=2.2.2=py36hb69df0a_2
  - mkl=2019.1=144
  - mkl_fft=1.0.6=py36hd81dba3_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - mypy=0.650=py36_0
  - mypy_extensions=0.4.1=py36_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py36h6bb024c_1
  - numpy=1.15.4=py36h7e9f1db_0
  - numpy-base=1.15.4=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - parso=0.3.1=py36_0
  - pcre=8.42=h439df22_0
  - pep8=1.7.1=py36_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=5.3.0=py36h34e0f95_0
  - pip=18.1=py36_0
  - prompt_toolkit=2.0.7=py36_0
  - ptyprocess=0.6.0=py36_0
  - pycodestyle=2.4.0=py36_0
  - pycparser=2.19=py36_0
  - pygments=2.2.0=py36_0
  - pyparsing=2.3.0=py36_0
  - pyqt=5.6.0=py36_2
  - python-dateutil=2.7.5=py36_0
  - pytz=2018.7=py36_0
  - qt=5.6.3=h8bf5577_3
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.20.2=py36hd81dba3_0
  - scipy=1.1.0=py36h7c811a0_2
  - setuptools=40.6.2=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.11.0=py36_1
  - sqlite=3.25.3=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py36h7b6447c_0
  - tqdm=4.28.1=py36h28b3542_0
  - traitlets=4.3.2=py36_0
  - typed-ast=1.1.0=py36h14c3975_0
  - wcwidth=0.1.7=py36_0
  - wheel=0.32.3=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - cuda92=1.0=0
  - faiss-gpu=1.4.0=py36_cuda9.2.148_1
  - pytorch=1.0.0=py3.6_cuda9.0.176_cudnn7.4.1_1
  - torchvision=0.2.1=py_2
  - pip:
    - faiss==1.4.0
    - furthest-sampling==0.0.0
    - losses==0.0.0
    - plyfile==0.6
    - sampling==0.0.0
    - torch==1.0.0
prefix: /home/ywang/anaconda3/envs/pytorch-1.0

